#!/usr/bin/env python3
"""Write a compact JSON summary for PQCFirm artifact runs.

The verification harness already produces detailed JSON files. This helper
collects the most important fields into one reviewer-friendly file so a run can
be checked without reading the terminal transcript.
"""
from __future__ import annotations

import argparse
import json
import os
import platform
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def read_json(path: Path, default: Any = None) -> Any:
    try:
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # keep summaries robust
        return {"_read_error": str(exc), "_path": str(path)}
    return default


def pct(value: Any) -> Any:
    try:
        return round(float(value) * 100.0, 3)
    except Exception:
        return value


def find_filtered_summary(results_dir: Path) -> dict[str, Any]:
    candidates = [
        results_dir / "mbedtls_filtered" / "filtered_summary.json",
        results_dir / "mbedtls_filtered_summary.json",
    ]
    for c in candidates:
        data = read_json(c)
        if isinstance(data, dict):
            return data
    return {}


def build_replication_summary(artifact_dir: Path, exit_code: int) -> dict[str, Any]:
    results = artifact_dir / "results"
    claim_matrix = read_json(results / "claim_matrix.json", {}) or {}
    failure = read_json(results / "failure_reproduction_status.json", {}) or {}
    diff = read_json(results / "differential_status.json", {}) or {}
    repeatability = read_json(results / "repeatability_summary.json", {}) or {}
    mbed_raw = read_json(results / "mbedtls_audit_status.json", {}) or {}
    mbed_filtered = find_filtered_summary(results)
    mutation = read_json(results / "mutation_summary.json", {}) or {}
    ground = read_json(results / "ground_truth_eval_summary.json", {}) or {}
    annotation = read_json(results / "annotation_consistency" / "agreement_summary.json", {}) or {}
    benchmark = read_json(results / "benchmark_data_quality_report.json", {}) or {}
    loc_count = read_json(results / "loc_count.json", {}) or {}

    passes: list[str] = []
    warnings: list[str] = []

    # The claim matrix may be either a list or dict depending on artifact version.
    if isinstance(claim_matrix, dict):
        for k, v in claim_matrix.items():
            if isinstance(v, dict):
                status = str(v.get("status") or v.get("result") or "").upper()
                if status == "PASS":
                    passes.append(k)
                elif status in {"WARN", "WARNING"}:
                    warnings.append(k)

    raw_precision = None
    if isinstance(mbed_raw, dict):
        raw_precision = mbed_raw.get("precision") or mbed_raw.get("assisted_precision")
    filtered_reduction = None
    filtered_yield = None
    if isinstance(mbed_filtered, dict):
        filtered_reduction = (
            mbed_filtered.get("triage_reduction")
            or mbed_filtered.get("finding_reduction")
            or mbed_filtered.get("reduction_rate")
            or mbed_filtered.get("filtered_reduction_rate")
        )
        filtered_yield = (
            mbed_filtered.get("assisted_candidate_yield")
            or mbed_filtered.get("assisted_candidate_precision")
            or mbed_filtered.get("assisted_precision")
            or mbed_filtered.get("candidate_precision")
        )

    # Current ESP32-S3 precision is regenerated by evaluate_pqcfirm.py.
    esp32 = {"true_positives": None, "findings": None, "precision": None}
    esp_csv = results / "ground_truth_annotations.csv"
    if esp_csv.exists():
        import csv
        with esp_csv.open("r", encoding="utf-8") as f:
            rows = list(csv.DictReader(f))
        total = len(rows)
        tps = sum(1 for r in rows if r.get("annotator_verdict") == "TP")
        esp32 = {"true_positives": tps, "findings": total, "precision": (tps / total if total else None)}

    summary = {
        "schema_version": "1.0",
        "mode": "replication",
        "timestamp_utc": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "command": "run_replication.bat / run_replication.sh -> artifact/verify_all.py",
        "exit_code": exit_code,
        "overall_status": "PASS" if exit_code == 0 else "FAIL",
        "environment": {
            "python": sys.version.split()[0],
            "platform": platform.platform(),
            "cwd": "<ARTIFACT_ROOT>",
        },
        "key_results": {
            "taxonomy_commits": 1043,
            "annotation_consistency": {
                "items": annotation.get("n_items"),
                "coders": annotation.get("n_coders"),
                "all_four_agree_rate": annotation.get("all_four_agree_rate"),
                "at_least_three_agree_rate": annotation.get("at_least_three_agree_rate"),
                "fleiss_kappa": annotation.get("fleiss_kappa"),
            },
            "esp32_precision": esp32,
            "mbedtls_raw": {
                "findings": mbed_raw.get("findings_total") or mbed_raw.get("total_findings") or mbed_raw.get("mbedtls_findings"),
                "sample_size": mbed_raw.get("audit_sample_size") or mbed_raw.get("sample_size") or 200,
                "assisted_precision": raw_precision,
                "note": "LLM-assisted static audit, not human manual audit.",
            },
            "mbedtls_filtered": {
                "raw_findings": mbed_filtered.get("raw_findings") or mbed_filtered.get("raw_findings_total"),
                "filtered_candidates": mbed_filtered.get("filtered_candidates") or mbed_filtered.get("filtered_candidate_findings"),
                "triage_reduction": filtered_reduction,
                "assisted_candidate_yield": filtered_yield,
                "note": "Source-filtered assisted triage-yield view, not production recall.",
            },
            "mutation_testing": mutation,
            "ground_truth_corpus": ground,
            "benchmark_validation": benchmark,
            "benchmark_loc_count": loc_count,
            "hardware_failure_logs": failure,
            "paired_trials": diff,
            "repeatability_n30": repeatability,
        },
        "artifact_files": {
            "claim_matrix": "artifact/results/claim_matrix.json",
            "claims_supported": "artifact/CLAIMS_SUPPORTED.md",
            "raw_mbedtls_status": "artifact/results/mbedtls_audit_status.json",
            "filtered_mbedtls_summary": "artifact/results/mbedtls_filtered/filtered_summary.json",
            "failure_status": "artifact/results/failure_reproduction_status.json",
            "differential_status": "artifact/results/differential_status.json",
            "repeatability_summary": "artifact/results/repeatability_summary.json",
            "loc_count": "artifact/results/loc_count.json",
        },
        "passes_seen_in_claim_matrix": passes,
        "warnings_seen_in_claim_matrix": warnings,
        "notes": [
            "The Mbed TLS audit is LLM-assisted triage, not a human manual audit.",
            "The filtered Mbed TLS view measures triage reduction and candidate yield, not recall.",
            "Hardware reproduction can be refreshed with run_hardware.bat or run_hardware_capture.py.",
            "The N=30 repeatability check is a fixed subset over included ESP32-S3 hardware serial rows, not a separate device experiment.",
        ],
    }
    return summary


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["replication"], default="replication")
    parser.add_argument("--exit-code", type=int, default=0)
    parser.add_argument("--artifact-dir", default=None)
    args = parser.parse_args()

    artifact_dir = Path(args.artifact_dir).resolve() if args.artifact_dir else Path(__file__).resolve().parents[1]
    results_dir = artifact_dir / "results"
    results_dir.mkdir(parents=True, exist_ok=True)

    summary = build_replication_summary(artifact_dir, args.exit_code)
    out = results_dir / "run_replication_summary.json"
    out.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    (results_dir / "latest_run_summary.json").write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")
    print(f"Run summary JSON written: {out}")
    return 0 if args.exit_code == 0 else args.exit_code


if __name__ == "__main__":
    raise SystemExit(main())
